# Generated by Django 4.0 on 2022-09-14 16:58

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('measurements_mobile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilesensor',
            name='transmission_type',
            field=models.CharField(choices=[('n/a', 'Na'), ('radio', 'Radio'), ('satellite', 'Satellite')], default='n/a', max_length=255),
        ),
        migrations.CreateModel(
            name='MobileSensorFisheryAssignment',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fishery', models.CharField(choices=[('demo', 'Demo'), ('dungeness crab', 'Dungeness Crab'), ('lobster', 'Lobster'), ('monkfish', 'Monkfish'), ('mussel farm', 'Mussel Farm'), ('n/a', 'Na'), ('scallop', 'Scallop'), ('snow crab', 'Snow Crab'), ('whelk', 'Whelk')], max_length=50, null=True)),
                ('fishing_technology', models.CharField(choices=[('aquaculture', 'Aquaculture'), ('gillnet', 'Gillnet'), ('n/a', 'Na'), ('ropeless gear', 'Ropeless Gear')], max_length=50, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('buoy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurements_mobile.mobilesensor')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='mobilesensorfisheryassignment',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', django.db.models.expressions.F('start_date'))), name='valid_fishery_assignment_date'),
        ),
    ]
