# Generated by Django 4.0 on 2022-09-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements_mobile', '0002_mobilesensor_transmission_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilesensor',
            name='transmission_type',
        ),
        migrations.AddField(
            model_name='mobilesensorfisheryassignment',
            name='transmission_type',
            field=models.CharField(choices=[('n/a', 'Na'), ('radio', 'Radio'), ('satellite', 'Satellite')], default='n/a', max_length=255),
        ),
    ]
